### ISSUE TITLE
Secondary Traits Issue

### ISSUE THREAD

**Issue by RinVindor** [CarterDC/mage-fr#63]
Testing things out and loving it but I did notice that when making a Merit and then going to Active Effects to create a merit active effect for increasing Health levels I noticed that only Willpower and Initiative are options. Not sure if you've already got that on your list of plans to add in.

**Comment by CarterDC** [comment]
There's no plan to make health compatible with AE. It might lead to very nasty bugs (I've tried ^^).
You can however try it for yourself by using the vanilla AE sheet that's available with the gear button in the title bar for ActiveEffects. (you'll have access to anything since you can type the whole string, but still it's unwise ^^).
If you just need more health, you can use the context menu on the health flavor text to set it up. 
Also, disabling your players ability to use aggravated wounds might be a way to set them some permanent damages.
